linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose
    - gofmt
    - exportloopref
    - prealloc
    - gocritic
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
      - httpresponse
      - defers
      - ifaceassert
      - slog
      - waitgroup
  gocritic:
    enabled-tags:
       - diagnostic
       - experimental
       - opinionated
       - performance
       - style

run:
  timeout: 10m
  go: '1.18'
  modules-download-mode: readonly